version: '3.1'
services:
  db:
    image: mysql/mysql-server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'mercadolivro'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"